In [4]:
import torch

In [5]:
m1 = torch.FloatTensor([3,3])
m1

tensor([3., 3.])

브로드캐스팅(Broadcasting)크기가 다른 행렬 또는 텐서에 대해서 사칙연산을 수행할때 Python에서는 자동으로 크기를 맞춰서 연산을 수행

In [7]:
# Vector + Scalarpermalink
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
m1+m2

tensor([[4., 5.]])

행렬 곱셈 & 곱셈 행렬 곱셈(.matmul) vs 원소 별 곱셈(.null)

In [9]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1 : ',m1.shape) # 2 x 2
print('Shape of Matrix 2 : ',m2.shape) # 2 x 1

Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])


In [11]:
# 행렬 곱셈(matrix mutiplication)
m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [13]:
#곱셈
m1*m2

tensor([[1., 2.],
        [6., 8.]])

In [14]:
m1.mul(m2)

tensor([[1., 2.],
        [6., 8.]])

In [17]:
t = torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [18]:
print(t.mean())

tensor(2.5000)


In [19]:
print(t.mean(dim=0)) # (행, 열)에서 행(0) 제거(즉, 열 별로 평균)
print(t.mean(dim=1)) # (행, 열)에서 열(1) 제거(즉, 행 별로 평균)

tensor([2., 3.])
tensor([1.5000, 3.5000])


In [20]:
t = torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [21]:
t.sum()

tensor(10.)

In [22]:
print(t.sum(dim=0)) # (행, 열)에서 행(0) 제거(즉, 열 별로 덧셈)
print(t.sum(dim=1)) # (행, 열)에서 열(1) 제거(즉, 행 별로 덧셈)
print(t.sum(dim=-1)) # (행, 열)에서 열(-1) 제거(행 별로 덧셈)

tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [24]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.max())
print(t.max(dim=0)) # (행, 열)에서 행(0) 제거(즉, 열 별로 최대)
print(t.max(dim=1)) # (행, 열)에서 열(1) 제거(즉, 행 별로 최대)
print(t.max(dim=-1)) # (행, 열)에서 열(-1) 제거(즉, 행 별로 최대)


tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


view:원소의 수를 유지하면서 텐서의 크기변경. 파이토치 텐서의 뷰(View)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 합니다. Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경

In [25]:
import numpy as np
t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)
print(ft.view([-1,3])) # 원소가 12개 이므로 열을 3개 유지, 즉 행은 4개 나옴
print(ft.view([-1,3]).shape) # 4행 3열
print(ft.view([3,-1])) # 원소가 12개 이므로 행을 3개 유지, 즉 열은 4개 나옴
print(ft.view([3,-1]).shape) # 3행 4열
print(ft.view([5,-1])) # 원소가 12개 이므로 행을 5개 유지해야 하므로 오류 발생

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4])


RuntimeError: shape '[5, -1]' is invalid for input of size 12

[3차원->3차원]
3차원 텐서에서 3차원 텐서로 차원은 유지하되, 크기(shape)를 바꾸는 작업

In [27]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


squeeze:1차원을 제거

In [28]:
ft= torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [29]:
ft = torch.Tensor([0,1,2])
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

print('----------------')
#view 로도 구현 가능
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
----------------
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [33]:
t = np.array([[[0,1,2],
               [3,4,5]],
               [[6,7,8],
               [9,10,11]],
               [[0,1,2],
               [3,4,5]],
               [[6,7,8],
               [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([4, 2, 3])
