In [54]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [55]:
torch.manual_seed(1)

In [56]:
# 데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

# 모델을 선언 및 초기화. 단순 선형 회귀
model = nn.Linear(1,1)
model

Linear(in_features=1, out_features=1, bias=True)

In [57]:
# modle.parameters()를 사용하여 W와 b 출력
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [58]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [59]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    # H(x) 계산
		prediction = model(x_train)

		# cost 계산
		cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 평균제곱오차

		# cost로 H(x)로 개선
		optimizer.zero_grad() # gradient를 0으로 초기화
		cost.backward() # 비용함수를 미분하여 gradient 계산
		optimizer.step() # W와 b를 업데이트

		# 100번 마다 로그출력
		if epoch % 100 == 0:
			print('Epoch {:4d}/{}  Cost : {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000  Cost : 13.103541
Epoch  100/2000  Cost : 0.002791
Epoch  200/2000  Cost : 0.001724
Epoch  300/2000  Cost : 0.001066
Epoch  400/2000  Cost : 0.000658
Epoch  500/2000  Cost : 0.000407
Epoch  600/2000  Cost : 0.000251
Epoch  700/2000  Cost : 0.000155
Epoch  800/2000  Cost : 0.000096
Epoch  900/2000  Cost : 0.000059
Epoch 1000/2000  Cost : 0.000037
Epoch 1100/2000  Cost : 0.000023
Epoch 1200/2000  Cost : 0.000014
Epoch 1300/2000  Cost : 0.000009
Epoch 1400/2000  Cost : 0.000005
Epoch 1500/2000  Cost : 0.000003
Epoch 1600/2000  Cost : 0.000002
Epoch 1700/2000  Cost : 0.000001
Epoch 1800/2000  Cost : 0.000001
Epoch 1900/2000  Cost : 0.000000
Epoch 2000/2000  Cost : 0.000000


In [60]:
# 임의의 입력 4를 선언
new_var = torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y 저장
pred_y = model(new_var)
#y = 2x
print('훈련 후 입력이 4일 때의 예측값 :',pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [61]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


다중선형회귀 구현하기

In [62]:
torch.manual_seed(1)

In [63]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [64]:
# 모델 선언 input_dim = 3 , output_dim = 1
model = nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [65]:
# lr=1e-5 학습률(learning rate)은 0.00001
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [66]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    # H(x) 계산
		prediction = model(x_train)
		# cost 계산
		cost = F.mse_loss(prediction, y_train)
		# cost로 H(x) 개선
		optimizer.zero_grad()
		cost.backward()
		optimizer.step()

		# 100번 마다 로그출력
		if epoch % 100 == 0:
			print('Epoch {:4d}/{}  Cost : {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000  Cost : 31667.599609
Epoch  100/2000  Cost : 0.225993
Epoch  200/2000  Cost : 0.223911
Epoch  300/2000  Cost : 0.221941
Epoch  400/2000  Cost : 0.220059
Epoch  500/2000  Cost : 0.218271
Epoch  600/2000  Cost : 0.216575
Epoch  700/2000  Cost : 0.214950
Epoch  800/2000  Cost : 0.213413
Epoch  900/2000  Cost : 0.211952
Epoch 1000/2000  Cost : 0.210559
Epoch 1100/2000  Cost : 0.209230
Epoch 1200/2000  Cost : 0.207967
Epoch 1300/2000  Cost : 0.206762
Epoch 1400/2000  Cost : 0.205618
Epoch 1500/2000  Cost : 0.204529
Epoch 1600/2000  Cost : 0.203481
Epoch 1700/2000  Cost : 0.202486
Epoch 1800/2000  Cost : 0.201539
Epoch 1900/2000  Cost : 0.200634
Epoch 2000/2000  Cost : 0.199770


In [68]:
# 임의의 입력 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])
# 입력한 값에 대해서 예측값 y를 리턴받아서 pred_y 저장
pred_y = model(new_var)
print('훈련 후 [73, 80, 75] 예측값 :',pred_y)

훈련 후 [73, 80, 75] 예측값 : tensor([[151.2306]], grad_fn=<AddmmBackward0>)


In [69]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
