In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [11]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드
torch.manual_seed(1)

In [12]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [13]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [14]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
# y = Wx+b
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [15]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [16]:
# h = 0*x + 0
hyopthesis = x_train*W + b
print(hyopthesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [17]:
# 비용함수 선언하기
cost = torch.mean(hyopthesis - y_train)**2
print(cost)

tensor(16., grad_fn=<PowBackward0>)


확률적경사하강법 SGD 사용하고

lr 학습률(learnig rate)를 의미

In [19]:
import torch.optim as optim

optimizer = optim.SGD([W, b], lr=0.01)

In [20]:
# gradient를 0으로 초기화
optimizer.zero_grad()
# 비용 함수를 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

In [23]:
# 전체코드
# 데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

# 원하는 만큼 경사 하강법 반복
nb_epochs = 1999
for epoch in range(nb_epochs+1):
    # H(x) 계산
		hyopthesis = x_train * W + b

		# cost 계산
		cost = torch.mean((hyopthesis - y_train)**2)

		# cost로 H(x)로 개선
		optimizer.zero_grad()
		cost.backward()
		optimizer.step()

		# 100번 마다 로그출력
		if epoch % 100 == 0:
			print('Epoch {:4d}/{} W : {:.3f}, b : {:.3f}, Cost : {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1999 W : 0.187, b : 0.080, Cost : 18.666666
Epoch  100/1999 W : 1.746, b : 0.578, Cost : 0.048171
Epoch  200/1999 W : 1.800, b : 0.454, Cost : 0.029767
Epoch  300/1999 W : 1.843, b : 0.357, Cost : 0.018394
Epoch  400/1999 W : 1.876, b : 0.281, Cost : 0.011366
Epoch  500/1999 W : 1.903, b : 0.221, Cost : 0.007024
Epoch  600/1999 W : 1.924, b : 0.174, Cost : 0.004340
Epoch  700/1999 W : 1.940, b : 0.136, Cost : 0.002682
Epoch  800/1999 W : 1.953, b : 0.107, Cost : 0.001657
Epoch  900/1999 W : 1.963, b : 0.084, Cost : 0.001024
Epoch 1000/1999 W : 1.971, b : 0.066, Cost : 0.000633
Epoch 1100/1999 W : 1.977, b : 0.052, Cost : 0.000391
Epoch 1200/1999 W : 1.982, b : 0.041, Cost : 0.000242
Epoch 1300/1999 W : 1.986, b : 0.032, Cost : 0.000149
Epoch 1400/1999 W : 1.989, b : 0.025, Cost : 0.000092
Epoch 1500/1999 W : 1.991, b : 0.020, Cost : 0.000057
Epoch 1600/1999 W : 1.993, b : 0.016, Cost : 0.000035
Epoch 1700/1999 W : 1.995, b : 0.012, Cost : 0.000022
Epoch 1800/1999 W : 1.996, 

In [24]:
# y = 1.997*x + 0.008   1==> 2 , 2==> 4


In [25]:
w = torch.tensor(2.0, requires_grad=True)
nb_epochs = 20
for eopch in range(nb_epochs+1):
    z = 2 * w
    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


In [26]:
w = torch.tensor(2.0 , requires_grad=True)
y = w**2
z = 2*y + 5
z.backward()
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0
